# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@0.1.2
      with:
        # A regular expression of files to include in our find and replace
        include: # optional, default is .*
        # A regular expression of files to exclude in our find and replace
        exclude: # optional, default is .git
        # The string we want to replace
        find: 
        # The new string to replace with
        replace: 
